version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - vite.config.js
    - .platform/**/*
    - .ebextensions/**/*
    - app/**/*
    - artisan
    - bootstrap/**/*
    - composer.json
    - composer.lock
    - config/**/*
    - database/**/*
    - package-lock.json
    - package.json
    - public/**/*
    - resources/**/*
    - routes/*
    - storage/**/*
